name: Set up gitrail
description: Install gitrail and add it to PATH
author: Songmu

runs:
  using: composite
  steps:
    - name: Install gitrail
      shell: bash
      run: |
        bash "${GITHUB_ACTION_PATH}/action.sh"
      env:
        # Authenticate gh attestation verify.
        GH_TOKEN: ${{ github.token }}

branding:
  icon: git-commit
  color: blue
