name: Set up gitrail
description: Install gitrail and add it to PATH
author: Songmu

runs:
  using: composite
  steps:
    - name: Install gitrail
      shell: bash
      run: |
        version="v0.0.23"
        bindir="${RUNNER_TEMP%/}/gitrail/bin"

        sh "${GITHUB_ACTION_PATH}/install.sh" \
          -b "${bindir}" "${version}"
        echo "${bindir}" >> "${GITHUB_PATH}"
      env:
        # Authenticate gh attestation verify.
        GH_TOKEN: ${{ github.token }}

branding:
  icon: git-commit
  color: blue
