#!/bin/sh
set -e
# Code generated by godzil. DO NOT EDIT.
# It is based on the one generated by godownloader.

usage() {
  this=$1
  cat <<EOF
$this: download go binaries for Songmu/gitrail

Usage: $this [-b] bindir [-d] [tag]
  -b sets bindir or installation directory, Defaults to ./bin
  -d turns on debug logging
   [tag] is a tag from
   https://github.com/Songmu/gitrail/releases
   If tag is missing, then the latest will be used.

 Generated by godownloader and godzil
  https://github.com/goreleaser/godownloader
  https://github.com/Songmu/godzil

EOF
  exit 2
}

parse_args() {
  #BINDIR is ./bin unless set be ENV
  # over-ridden by flag below

  BINDIR=${BINDIR:-./bin}
  while getopts "b:dh?x" arg; do
    case "$arg" in
      b) BINDIR="$OPTARG" ;;
      d) log_set_priority 10 ;;
      h | \?) usage "$0" ;;
      x) set -x ;;
    esac
  done
  shift $((OPTIND - 1))
  TAG=$1
}
# this function wraps all the destructive operations
# if a curl|bash cuts off the end of the script due to
# network, either nothing will happen or will syntax error
# out preventing half-done work
cleanup() {
  if [ -n "${tmpdir:-}" ]; then
    rm -rf "${tmpdir}"
    tmpdir=
  fi
}
execute() {
  log_debug "downloading files into ${tmpdir}"
  http_download "${tmpdir}/${TARBALL}" "${TARBALL_URL}"
  verify "${tmpdir}/${TARBALL}"
  srcdir="${tmpdir}/${NAME}"
  (cd "${tmpdir}" && untar "${TARBALL}")
  test ! -d "${BINDIR}" && install -d "${BINDIR}"
  for binexe in $BINARIES; do
    if [ "$OS" = "windows" ]; then
      binexe="${binexe}.exe"
    fi
    install "${srcdir}/${binexe}" "${BINDIR}/"
    log_info "installed ${BINDIR}/${binexe}"
  done
}
get_binaries() {
  case "$PLATFORM" in
    darwin/386) BINARIES="gitrail" ;;
    darwin/amd64) BINARIES="gitrail" ;;
    darwin/arm64) BINARIES="gitrail" ;;
    darwin/armv6) BINARIES="gitrail" ;;
    linux/386) BINARIES="gitrail" ;;
    linux/amd64) BINARIES="gitrail" ;;
    linux/arm64) BINARIES="gitrail" ;;
    linux/armv6) BINARIES="gitrail" ;;
    windows/386) BINARIES="gitrail" ;;
    windows/amd64) BINARIES="gitrail" ;;
    windows/arm64) BINARIES="gitrail" ;;
    windows/armv6) BINARIES="gitrail" ;;
    *)
      log_crit "platform $PLATFORM is not supported.  Make sure this script is up-to-date and file request at https://github.com/${PREFIX}/issues/new"
      exit 1
      ;;
  esac
}
tag_to_version() {
  if [ -z "${TAG}" ]; then
    log_info "checking GitHub for latest tag"
  else
    log_info "checking GitHub for tag '${TAG}'"
  fi
  REALTAG=$(github_release "$OWNER/$REPO" "${TAG}") && true
  if test -z "$REALTAG"; then
    log_crit "unable to find '${TAG}' - use 'latest' or see https://github.com/${PREFIX}/releases for details"
    exit 1
  fi
  # if version starts with 'v', remove it
  TAG="$REALTAG"
  VERSION=${TAG}
}
adjust_format() {
  case ${OS} in
    darwin) FORMAT=zip ;;
    windows) FORMAT=zip ;;
  esac
  # change format (tar.gz or zip) based on OS
  true
}
adjust_os() {
  # adjust archive name based on OS
  true
}
adjust_arch() {
  # adjust archive name based on ARCH
  true
}

gh_supports_safe_attestation() {
  # gh <= 2.92.0 may expose credentials to untrusted TUF mirrors when
  # verifying attestations (GHSA-8xvp-7hj6-mcj9); require the patched release.
  gh --version 2>/dev/null | awk '
    NR == 1 {
      if ($3 !~ /^[0-9]+\.[0-9]+\.[0-9]+$/) {
        exit 1
      }
      split($3, version, ".")
      exit !(version[1] > 2 || (version[1] == 2 && version[2] >= 93))
    }
    END {
      if (NR == 0) {
        exit 1
      }
    }
  '
}
uses_trusted_release_workflow() {
  _gitrail_version=${VERSION#v}
  _gitrail_major=${_gitrail_version%%.*}
  _gitrail_remainder=${_gitrail_version#*.}
  _gitrail_minor=${_gitrail_remainder%%.*}
  _gitrail_patch=${_gitrail_remainder#*.}
  _gitrail_patch=${_gitrail_patch%%[-+]*}

  [ "$_gitrail_major" -gt 0 ] ||
    [ "$_gitrail_minor" -gt 0 ] ||
    [ "$_gitrail_patch" -ge 13 ]
}
verify() {
  artifact=$1
  if is_command gh &&
    gh_supports_safe_attestation &&
    gh attestation verify --help >/dev/null 2>&1; then
    log_info "verifying build provenance for ${artifact##*/}"
    if uses_trusted_release_workflow; then
      gh attestation verify "$artifact" \
        --repo "$OWNER/$REPO" \
        --signer-workflow "$OWNER/$REPO/.github/workflows/release-reusable.yaml"
    else
      gh attestation verify "$artifact" --repo "$OWNER/$REPO"
    fi
    log_info "verified build provenance for ${artifact##*/}"
    return
  fi
  log_info "build provenance verification unavailable; falling back to SHA256"
  http_download "${tmpdir}/${CHECKSUM}" "${CHECKSUM_URL}"
  hash_sha256_verify "$artifact" "${tmpdir}/${CHECKSUM}"
}

cat /dev/null <<EOF
------------------------------------------------------------------------
shlib 2026.08.30 - portable shell functions for install scripts

https://github.com/client9/shlib
Public domain - http://unlicense.org
https://github.com/client9/shlib/blob/master/LICENSE.md

but credit (and pull requests) appreciated.
------------------------------------------------------------------------
EOF
is_command() {
  command -v "$1" >/dev/null
}
echoerr() {
  echo "$@" 1>&2
}

_shlib_logp=6

log_set_priority() {
  _shlib_logp="$1"
}

log_priority() {
  if test -z "${1-}"; then
    echo "$_shlib_logp"
    return
  fi
  [ "$1" -le "$_shlib_logp" ]
}

log_tag() {
  case $1 in
    0) echo "emerg" ;;
    1) echo "alert" ;;
    2) echo "crit" ;;
    3) echo "err" ;;
    4) echo "warning" ;;
    5) echo "notice" ;;
    6) echo "info" ;;
    7) echo "debug" ;;
    *) echo "$1" ;;
  esac
}

log_debug() {
  log_priority 7 || return 0
  echoerr "$(log_prefix)" "$(log_tag 7)" "$@"
}

log_info() {
  log_priority 6 || return 0
  echoerr "$(log_prefix)" "$(log_tag 6)" "$@"
}

log_err() {
  log_priority 3 || return 0
  echoerr "$(log_prefix)" "$(log_tag 3)" "$@"
}

log_crit() {
  log_priority 2 || return 0
  echoerr "$(log_prefix)" "$(log_tag 2)" "$@"
}

uname_os() {
  _shlib_os=$(uname -s | tr '[:upper:]' '[:lower:]')

  case "$_shlib_os" in
    msys*) _shlib_os="windows" ;;
    mingw*) _shlib_os="windows" ;;
    cygwin*) _shlib_os="windows" ;;
    win*) _shlib_os="windows" ;;
  esac

  if [ "$_shlib_os" = "sunos" ]; then
    if [ "$(uname -o 2>/dev/null)" = "illumos" ]; then
      _shlib_os="illumos"
    else
      _shlib_os="solaris"
    fi
  fi

  echo "$_shlib_os"
}
uname_arch() {
  _shlib_arch=$(uname -m)
  case $_shlib_arch in
    x86_64) _shlib_arch="amd64" ;;
    i86pc) _shlib_arch="amd64" ;;
    x86) _shlib_arch="386" ;;
    i686) _shlib_arch="386" ;;
    i386) _shlib_arch="386" ;;
    aarch64) _shlib_arch="arm64" ;;
    armv5*) _shlib_arch="armv5" ;;
    armv6*) _shlib_arch="armv6" ;;
    armv7*) _shlib_arch="armv7" ;;
    loongarch64) _shlib_arch="loong64" ;;
  esac
  echo "${_shlib_arch}"
}
uname_os_check() {
  _shlib_os=$(uname_os)
  case "$_shlib_os" in
    aix) return 0 ;;
    darwin) return 0 ;;
    dragonfly) return 0 ;;
    freebsd) return 0 ;;
    linux) return 0 ;;
    android) return 0 ;;
    midnightbsd) return 0 ;;
    nacl) return 0 ;;
    netbsd) return 0 ;;
    openbsd) return 0 ;;
    plan9) return 0 ;;
    solaris) return 0 ;;
    illumos) return 0 ;;
    ios) return 0 ;;
    js) return 0 ;;
    wasip1) return 0 ;;
    windows) return 0 ;;
  esac
  log_crit "uname_os_check '$(uname -s)' got converted to '$_shlib_os' which is not a recognized OS name"
  return 1
}
uname_arch_check() {
  _shlib_arch=$(uname_arch)
  case "$_shlib_arch" in
    386) return 0 ;;
    amd64) return 0 ;;
    arm64) return 0 ;;
    armv5) return 0 ;;
    armv6) return 0 ;;
    armv7) return 0 ;;
    ppc64) return 0 ;;
    ppc64le) return 0 ;;
    mips) return 0 ;;
    mipsle) return 0 ;;
    mips64) return 0 ;;
    mips64le) return 0 ;;
    s390x) return 0 ;;
    riscv64) return 0 ;;
    loong64) return 0 ;;
    amd64p32) return 0 ;;
  esac
  log_crit "uname_arch_check '$(uname -m)' got converted to '$_shlib_arch' which is not a recognized architecture name"
  return 1
}
untar() {
  _shlib_tarball=$1
  case "${_shlib_tarball}" in
    *.tar.gz | *.tgz) tar -xzf "${_shlib_tarball}" ;;
    *.tar.bz2 | *.tbz | *.tbz2) tar -xjf "${_shlib_tarball}" ;;
    *.tar.xz | *.txz) tar -xJf "${_shlib_tarball}" ;;
    *.tar.zst | *.tzst)
      if ! is_command zstd; then
        log_err "untar zstd is required to unpack ${_shlib_tarball}"
        return 1
      fi
      zstd -dc "${_shlib_tarball}" | tar -xf -
      ;;
    *.tar) tar -xf "${_shlib_tarball}" ;;
    *.zip)
      if ! is_command unzip; then
        log_err "untar unzip is required to unpack ${_shlib_tarball}"
        return 1
      fi
      unzip "${_shlib_tarball}"
      ;;
    *)
      log_err "untar unknown archive format for ${_shlib_tarball}"
      return 1
      ;;
  esac
}
http_download_curl() {
  _shlib_local_file=$1
  _shlib_source_url=$2
  _shlib_header=${3-}
  if [ -z "$_shlib_header" ]; then
    curl -fsSL -o "$_shlib_local_file" "$_shlib_source_url"
  else
    curl -fsSL -H "$_shlib_header" -o "$_shlib_local_file" "$_shlib_source_url"
  fi
}

http_download_wget() {
  _shlib_local_file=$1
  _shlib_source_url=$2
  _shlib_header=${3-}
  if [ -z "$_shlib_header" ]; then
    wget -q -O "$_shlib_local_file" "$_shlib_source_url"
  else
    wget -q --header "$_shlib_header" -O "$_shlib_local_file" "$_shlib_source_url"
  fi
}
http_download_fetch() {
  _shlib_local_file=$1
  _shlib_source_url=$2
  _shlib_header=${3-}

  if [ -z "$_shlib_header" ]; then
    fetch -q -o "$_shlib_local_file" "$_shlib_source_url"
    return
  fi

  case "$_shlib_header" in
    [Aa]ccept:*)
      _shlib_accept=${_shlib_header#*:}
      _shlib_accept=${_shlib_accept# }
      HTTP_ACCEPT="$_shlib_accept" fetch -q -o "$_shlib_local_file" "$_shlib_source_url"
      return
      ;;
  esac

  log_crit "http_download fetch cannot send '${_shlib_header%%:*}' headers; install curl or wget"
  return 1
}

http_download_ftp() {
  _shlib_local_file=$1
  _shlib_source_url=$2
  _shlib_header=${3-}

  if [ -z "$_shlib_header" ]; then
    ftp -V -o "$_shlib_local_file" "$_shlib_source_url"
    return
  fi

  case "$_shlib_header" in
    [Aa]ccept:*)
      log_crit "http_download ftp cannot override the Accept header; install curl or wget"
      return 1
      ;;
  esac

  if ftp -Z </dev/null 2>&1 | grep '\[-H ' >/dev/null 2>&1; then
    ftp -V -H "$_shlib_header" -o "$_shlib_local_file" "$_shlib_source_url"
    return
  fi

  log_crit "http_download ftp cannot send '${_shlib_header%%:*}' headers; install curl or wget"
  return 1
}

http_download_python() {
  _shlib_local_file=$1
  _shlib_source_url=$2
  _shlib_header=${3-}

  python3 -c '
import sys, urllib.request

dest, url, hdr = sys.argv[1], sys.argv[2], sys.argv[3]
req = urllib.request.Request(url)
if hdr:
    name, _, value = hdr.partition(":")
    req.add_header(name.strip(), value.strip())
try:
    resp = urllib.request.urlopen(req, timeout=60)
    out = open(dest, "wb")
    while True:
        buf = resp.read(65536)
        if not buf:
            break
        out.write(buf)
    out.close()
except Exception as err:
    sys.stderr.write("python3: %s: %s\n" % (url, err))
    sys.exit(1)
' "$_shlib_local_file" "$_shlib_source_url" "$_shlib_header"
}

http_download_node() {
  _shlib_local_file=$1
  _shlib_source_url=$2
  _shlib_header=${3-}

  if is_command node; then
    _shlib_node=node
  else
    _shlib_node=nodejs
  fi

  "$_shlib_node" -e '
const fs = require("fs");
const { Readable } = require("stream");

const dest = process.argv[1], url = process.argv[2], hdr = process.argv[3];
if (typeof fetch !== "function") {
  process.stderr.write("node: fetch() requires node 18 or newer\n");
  process.exit(1);
}
const opts = {};
if (hdr) {
  const i = hdr.indexOf(":");
  opts.headers = { [hdr.slice(0, i).trim()]: hdr.slice(i + 1).trim() };
}
fetch(url, opts).then(function (r) {
  if (!r.ok) throw new Error("HTTP " + r.status + " " + r.statusText);
  return new Promise(function (resolve, reject) {
    const out = fs.createWriteStream(dest);
    out.on("finish", resolve);
    out.on("error", reject);
    Readable.fromWeb(r.body).pipe(out);
  });
}).catch(function (e) {
  process.stderr.write("node: " + url + ": " + e.message + "\n");
  process.exit(1);
});
' "$_shlib_local_file" "$_shlib_source_url" "$_shlib_header"
}

http_download() {
  log_debug "http_download $2"
  if is_command curl; then
    http_download_curl "$@"
    return
  elif is_command wget; then
    http_download_wget "$@"
    return
  elif is_command fetch; then
    http_download_fetch "$@"
    return
  elif is_command ftp; then
    http_download_ftp "$@"
    return
  elif is_command python3; then
    http_download_python "$@"
    return
  elif is_command node || is_command nodejs; then
    http_download_node "$@"
    return
  fi
  log_crit "http_download unable to find curl, wget, fetch, ftp, python3 or node"
  return 1
}

http_copy() {
  _shlib_http_copy_dir=${TMPDIR:-/tmp}
  _shlib_tmp=$(mktemp "${_shlib_http_copy_dir%/}/shlib.XXXXXXXXXX") || return 1
  if ! http_download "${_shlib_tmp}" "$1" "${2-}"; then
    rm -f "${_shlib_tmp}"
    return 1
  fi
  cat "${_shlib_tmp}"
  _shlib_rc=$?
  rm -f "${_shlib_tmp}"
  return $_shlib_rc
}

github_release() {
  _shlib_owner_repo=$1
  _shlib_version=${2-}
  test -z "$_shlib_version" && _shlib_version="latest"
  _shlib_giturl="https://github.com/${_shlib_owner_repo}/releases/${_shlib_version}"
  _shlib_json=$(http_copy "$_shlib_giturl" "Accept:application/json")
  test -z "$_shlib_json" && return 1
  _shlib_flat=$(echo "$_shlib_json" | tr -s '\n' ' ')
  _shlib_version=$(printf '%s\n' "$_shlib_flat" | sed 's/.*"tag_name":"//' | sed 's/".*//')
  test -z "$_shlib_version" && return 1

  case "$_shlib_version" in
    *[!A-Za-z0-9._+-]* | "")
      log_err "github_release did not find a tag at ${_shlib_giturl} (got '$(echo "$_shlib_version" | cut -c1-40)')"
      return 1
      ;;
  esac

  echo "$_shlib_version"
}
hash_sha256() {
  if [ -z "${1-}" ]; then
    set --
  else
    set -- "$1"
  fi
  if is_command gsha256sum; then
    _shlib_hash=$(gsha256sum "$@") || return 1
    echo "$_shlib_hash" | cut -d ' ' -f 1
  elif is_command sha256sum; then
    _shlib_hash=$(sha256sum "$@") || return 1
    echo "$_shlib_hash" | cut -d ' ' -f 1
  elif is_command shasum; then
    _shlib_hash=$(shasum -a 256 "$@" 2>/dev/null) || return 1
    echo "$_shlib_hash" | cut -d ' ' -f 1
  elif is_command openssl; then
    _shlib_hash=$(openssl dgst -sha256 "$@") || return 1
    echo "$_shlib_hash" | awk '{print $NF}'
  else
    log_crit "hash_sha256 unable to find command to compute sha-256 hash"
    return 1
  fi
}

hash_sha256_verify() {
  _shlib_target=$1
  _shlib_checksums=${2-}

  if [ -z "$_shlib_checksums" ]; then
    log_err "hash_sha256_verify checksum file not specified in arg2"
    return 1
  fi

  _shlib_basename=${_shlib_target##*/}

  _shlib_want=$(awk -v name="$_shlib_basename" '
    {
      f = $2
      sub(/^\*/, "", f)
      sub(/.*\//, "", f)
      if (f == name) print $1
    }' "$_shlib_checksums" 2>/dev/null)

  if [ -z "$_shlib_want" ]; then
    log_err "hash_sha256_verify unable to find checksum for '${_shlib_target}' in '${_shlib_checksums}'"
    return 1
  fi

  _shlib_nwant=$(printf '%s\n' "$_shlib_want" | wc -l | tr -d ' ')
  if [ "$_shlib_nwant" != "1" ]; then
    log_err "hash_sha256_verify multiple checksums for '${_shlib_basename}' in '${_shlib_checksums}'"
    return 1
  fi

  _shlib_got=$(hash_sha256 "$_shlib_target")
  if [ "$_shlib_want" != "$_shlib_got" ]; then
    log_err "hash_sha256_verify checksum for '$_shlib_target' did not verify ${_shlib_want} vs $_shlib_got"
    return 1
  fi
}
cat /dev/null <<EOF
------------------------------------------------------------------------
End of shlib 2026.08.30 functions
------------------------------------------------------------------------
EOF

PROJECT_NAME="gitrail"
OWNER=Songmu
REPO="gitrail"
FORMAT=tar.gz
OS=$(uname_os)
ARCH=$(uname_arch)
PREFIX="$OWNER/$REPO"

# use in logging routines
log_prefix() {
	echo "$PREFIX"
}
PLATFORM="${OS}/${ARCH}"
GITHUB_DOWNLOAD=https://github.com/${OWNER}/${REPO}/releases/download

uname_os_check "$OS"
uname_arch_check "$ARCH"

parse_args "$@"

get_binaries

tmpdir=$(mktemp -d)
trap cleanup 0
trap 'exit 1' HUP INT TERM

tag_to_version

adjust_format

adjust_os

adjust_arch

log_info "found version: ${VERSION} for ${TAG}/${OS}/${ARCH}"

NAME=${PROJECT_NAME}_${VERSION}_${OS}_${ARCH}
TARBALL=${NAME}.${FORMAT}
TARBALL_URL=${GITHUB_DOWNLOAD}/${TAG}/${TARBALL}
CHECKSUM=SHA256SUMS
CHECKSUM_URL=${GITHUB_DOWNLOAD}/${TAG}/${CHECKSUM}


execute

cleanup
trap - 0 HUP INT TERM
