name: tagpr
on:
  push:
    branches:
    - "main"
  workflow_dispatch:

jobs:
  tagpr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: write
      contents: write
      pull-requests: write
      issues: write
    steps:
    - name: checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: setup go
      uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
      with:
        go-version-file: go.mod
    - name: tagpr
      id: tagpr
      uses: Songmu/tagpr@e84001bd5dac8defa0c75b3913937d284a3b3660 # v1.20.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: dispatch release
      if: steps.tagpr.outputs.tag != ''
      env:
        GH_TOKEN: ${{ github.token }}
        TAG: ${{ steps.tagpr.outputs.tag }}
      run: gh workflow run release.yaml --ref "$TAG"
